# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtTest_v01.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(433, 323)
        self.buttonPressMe = QtWidgets.QPushButton(Dialog)
        self.buttonPressMe.setGeometry(QtCore.QRect(160, 240, 151, 41))
        self.buttonPressMe.setObjectName("buttonPressMe")
        self.lblYourName = QtWidgets.QLabel(Dialog)
        self.lblYourName.setGeometry(QtCore.QRect(160, 110, 131, 61))
        self.lblYourName.setObjectName("lblYourName")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonPressMe.setText(_translate("Dialog", "Press Me!"))
        self.lblYourName.setText(_translate("Dialog", "Hi my name is Bill."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
